CC=gcc
CFLAGS=-Wall
CP=copy
OPT_FLAG=-Os

all: cp

cp: $(CP).c
		$(CC) $(CFLAGS) $(OPT_FLAG) -c $(CP).c
		$(CC) $(CFLAGS) $(OPT_FLAG) $(CP).o -o $(CP).
clean:
		rm -f *.o $(CP). ?.txt ? valgrind-out.txt
